### ISSUE TITLE
Can I get a job offer from your company?

### ISSUE THREAD

**Issue by wupco** [ambionics/wrapwrap#1]
Hello, I am a job seeker currently studying in the United States.

Here is my resume:

I discovered your main idea 5 years before you did. (ABCD -> DCBA)
https://hackmd.io/@ZzDmROodQUynQsF9je3Q5Q/B1A2JIjjm
The conversion dictionary you are using was produced by a simple fuzzer I wrote and published at
https://github.com/wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT/tree/main
I didn't receive any credit or acknowledgment in your article.

Am I qualified to be an employee at your company? Can I get a summer internship?

**Comment by cfreal** [comment]
Hello @wupco,

First and foremost, [in my blogpost](https://www.ambionics.io/blog/wrapwrap-php-filters-suffix), **I credited and spent lots of time** describing **the work of others** including remsio and loknop. I could however have listed all my sources; which brings us to my second point.

To the best of my recollection, I did not use your fuzzer nor had read your blogpost. The character swap idea I got from the [error-based article from remsio](https://www.synacktiv.com/en/publications/php-filter-chains-file-read-from-error-based-oracle) (and maybe he got it from you). This is hardly the main idea of the algorithm though.

Now that this is out of the way, you clearly took part in the full picture of the php://filter research, so I'll happily credit you for your work, **as I did for everybody else**. However, due to your attitude I won't do any more work for you than accept a PR.

Regards,
Charles

**Comment by wupco** [comment]
> Hello @wupco,
> 
> First and foremost, [in my blogpost](https://www.ambionics.io/blog/wrapwrap-php-filters-suffix), **I credited and spent lots of time** describing **the work of others** including remsio and loknop. I could however have listed all my sources; which brings us to my second point.
> 
> To the best of my recollection, I did not use your fuzzer nor had read your blogpost. The character swap idea I got from the [error-based article from remsio](https://www.synacktiv.com/en/publications/php-filter-chains-file-read-from-error-based-oracle) (and maybe he got it from you). This is hardly the main idea of the algorithm though.
> 
> Now that this is out of the way, you clearly took part in the full picture of the php://filter research, so I'll happily credit you for your work, **as I did for everybody else**. However, due to your attitude I won't do any more work for you than accept a PR.
> 
> Regards, Charles

That's interesting.

Could you tell me why https://github.com/synacktiv/php_filter_chains_oracle_exploit/blob/main/filters_chain_oracle/core/bruteforcer.py#L192 is using `|convert.iconv.UTF8.CP930|dechunk` to present the "/", but you are using [(https://github.com/ambionics/wrapwrap/blob/main/wrapwrap.py#L322)](https://github.com/ambionics/wrapwrap/blob/650a92a967582bc27714f28789a4109f4686d799/wrapwrap.py#L322) which is totally same with my result https://github.com/wupco/PHP_INCLUDE_TO_SHELL_CHAR_DICT/blob/main/res/2f??  Could you please calculate the possibility?

**Comment by cfreal** [comment]
https://github.com/synacktiv/php_filter_chain_generator/blob/main/php_filter_chain_generator.py#L77

**Comment by wupco** [comment]
> https://github.com/synacktiv/php_filter_chain_generator/blob/main/php_filter_chain_generator.py#L77

https://www.synacktiv.com/en/publications/php-filters-chain-what-is-it-and-how-to-use-it#:~:text=Using%20the%20elements,chaining%20the%20filters.

**Comment by wupco** [comment]
> > https://github.com/synacktiv/php_filter_chain_generator/blob/main/php_filter_chain_generator.py#L77
> 
> https://www.synacktiv.com/en/publications/php-filters-chain-what-is-it-and-how-to-use-it#:~:text=Using%20the%20elements,chaining%20the%20filters.

They were just using my result, and gave me the credit.

**Comment by wupco** [comment]
https://github.com/synacktiv/php_filter_chain_generator/blob/main/php_filter_chain_generator.py#L8

also here

**Comment by cfreal** [comment]
I know the Synacktiv article cites you, and gives you credit. That's how it works: I reference an article that references your article. I didn't cite the sources of my sources, nor the sources of the sources of my sources, because nobody does this.

For instance, I didn't reference [Surprising CTF task solution using php://filter](https://gynvael.coldwind.pl/?id=671) in the blogpost, while we can agree it was the starting point (don't quote me on this, I don't want to forget another source) of the `php://filter` research.

Again, if you came to me stating that you wanted a reference in the blogpost / repo I would have complied in a blink. You come in with a passive aggressive attitude, persuaded that I have a personal vendetta that makes me cite everybody else but not you.

I have spent enough time on this "issue" already, PR or close, thanks.

**Comment by wupco** [comment]
You speak so righteously, as if you are the victim.  I sincerely hope that you will not harbor any regrets in the future, and may God bless you.
